# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 00:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181108_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 0, 36, 57, 119461, tzinfo=utc)),
        ),
    ]
