# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181113_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 0, 37, 45, 497651, tzinfo=utc)),
        ),
    ]
